name: functions
description: SRM timetable app backend
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

  csv: ^5.1.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

assets:
  - timetables/
